### ISSUE TITLE
Android missing compileOptions in build.gradle

### ISSUE THREAD

**Issue by axolotl0212** [RonRadtke/react-native-blob-util#200]
Cannot build Android app after upgrading to 0.17.0.

Lambda expression (Java 8) is used in Android source file

https://github.com/RonRadtke/react-native-blob-util/blob/977a5a908116ae8afa8b7d59efae4ffde81aaa56/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilPackage.java#L28
  
However `compileOptions` is not explicitly specified in `build.gradle`, leading to compilation error

Related issue in other repo: https://github.com/OneSignal/react-native-onesignal/issues/1235

Suggest adding the `compileOptions` to `build.gradle` to enable desugaring, as follow:

```
android {
    ...
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    ...
}
```

**Comment by chenyulun** [comment]
/android/build.gradle
```gradle
import com.android.build.gradle.BaseExtension

allprojects {
// ...
getSubprojects().each {
        Project currentProject = it
        currentProject.afterEvaluate {
            try {
                BaseExtension android = currentProject.extensions.getByName('android')
                android.compileOptions {
                    sourceCompatibility JavaVersion.VERSION_1_8
                    targetCompatibility JavaVersion.VERSION_1_8
                }
            } catch(e) {
            }
        }
    }
}

```
