### ISSUE TITLE
Problem with windows build and react-native-blob-util@0.22.0

### ISSUE THREAD

**Issue by szujak** [RonRadtke/react-native-blob-util#419]
Hello,

I was trying to update react-native-blob-utils to 0.22.0 version, but I faced issue with running my app.

react-native: 0.78.2
react-native-windows: 0.78.5
```
> npx @react-native-community/cli run-windows
...
21>C:\App\node_modules\react-native\ReactCommon\cxxreact\NativeToJsBridge.cpp(197,5): error C4996: 'facebook::react::SystraceSection': Use TraceSection [C:\App\node_modules\react-native-blob-util\node_modules\react-native-windows\ReactCommon\ReactCommon.vcxproj](compiling source file '../../../../react-native/ReactCommon/cxxreact/NativeToJsBridge.cpp')
21>C:\App\node_modules\react-native\ReactCommon\cxxreact\NativeToJsBridge.cpp(197,22): error C4996: 'facebook::react::SystraceSection::SystraceSection': Use TraceSection [C:\App\node_modules\react-native-blob-util\node_modules\react-native-windows\ReactCommon\ReactCommon.vcxproj](compiling source file '../../../../react-native/ReactCommon/cxxreact/NativeToJsBridge.cpp')
21>C:\App\node_modules\react-native\ReactCommon\cxxreact\NativeToJsBridge.cpp(232,9): error C4996: 'facebook::react::SystraceSection': Use TraceSection [C:\App\node_modules\react-native-blob-util\node_modules\react-native-windows\ReactCommon\ReactCommon.vcxproj](compiling source file '../../../../react-native/ReactCommon/cxxreact/NativeToJsBridge.cpp')
21>C:\App\node_modules\react-native\ReactCommon\cxxreact\NativeToJsBridge.cpp(232,26): error C4996: 'facebook::react::SystraceSection::SystraceSection': Use TraceSection [C:\App\node_modules\react-native-blob-util\node_modules\react-native-windows\ReactCommon\ReactCommon.vcxproj](compiling source file '../../../../react-native/ReactCommon/cxxreact/NativeToJsBridge.cpp')
...
```

Running in Visual Studio gives this errors

```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	MIDL5157	[msg]An invalid winmd file was specified for import [context]: C:\App\node_modules\react-native-blob-util\node_modules\react-native-windows\target\x64\Debug\Microsoft.ReactNative\Microsoft.ReactNative.winmd	ReactNativeBlobUtil	C:\App\node_modules\react-native-blob-util\windows\ReactNativeBlobUtil\ReactPackageProvider.idl	1		
Error	MIDL5157	[msg]An invalid winmd file was specified for import [context]: C:\App\windows\x64\Debug\ReactNativeBlobUtil.winmd	app	C:\App\windows\app\App.idl	1		
Error	MIDL1001	[msg]cannot open input file [context]Error opening or processing WinMD c:\app\node_modules\react-native-blob-util\node_modules\react-native-windows\target\x64\debug\microsoft.reactnative\microsoft.reactnative.winmd. HRESULT 0x80070003.	ReactNativeBlobUtil	C:\App\node_modules\react-native-blob-util\windows\ReactNativeBlobUtil\midlrt	1		
Error	MIDL1001	[msg]cannot open input file [context]Error opening or processing WinMD c:\app\windows\x64\debug\reactnativeblobutil.winmd. HRESULT 0x80070002.	app	C:\App\windows\app\midlrt	1		
```

Version 0.21.3 works fine with react-native 0.78.x

Any ideas how to solve this?

**Comment by anupriya13** [comment]
@szujak Did you try clean rebuild?

**Comment by szujak** [comment]
Yes, I removed all build files and node_modules folder from project, I also ran autolink before rebuild. Then I also tried to use `Clean` options in Visual Studio, but I still see this error.
I'm facing the same issue in v0.22.1

**Comment by anupriya13** [comment]
> Yes, I removed all build files and node_modules folder from project, I also ran autolink before rebuild. Then I also tried to use `Clean` options in Visual Studio, but I still see this error.
> I'm facing the same issue in v0.22.1

Okay, let me try to repro for 0.78 and update.

I didn't face any issue for 0.77 so far.

If it's due to version mismatch then will upgrade this repo to 0.78 and 0.79 in next minor releases.

**Comment by szujak** [comment]
I just added to packages.json 

```
"resolutions": {
    "react-native-blob-util/react-native": "0.78.2",
    "react-native-blob-util/react-native-windows": "0.78.5"
  },
```

and it looks that it fixed the issue with build

**Comment by anupriya13** [comment]
https://github.com/RonRadtke/react-native-blob-util/pull/422

**Comment by RonRadtke** [comment]
Forgot to link the issue.... Version published :)
Thanks!
